spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions

spark.sql.catalog.retail=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.retail.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog
spark.sql.catalog.retail.io-impl=org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.retail.warehouse=s3://iceberg-retail-bucket/warehouse/
spark.sql.catalog.retail.glue.region=ap-south-1

spark.sql.defaultCatalog=retail

spark.eventLog.enabled=true
spark.eventLog.dir=/home/iceberg/spark-events
spark.history.fs.logDirectory=/home/iceberg/spark-events

spark.sql.catalogImplementation=in-memory
